@baseUrl=http://localhost:5000/authors

### RITORNA LA LISTA DEGLI AUTORI
GET {{baseUrl}}
### RITORNA IL SINGOLO AUTORE
GET {{baseUrl}}/66a93681fe704129bec62ea5
### CREA UN NUOVO AUTORE
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "example",
  "surname": "example",
  "birthDate": "01/01/2000",
  "email": "example@example.com",
  "avatar": "https://picsum.photos/300/300"
}
### MODIFICA UN AUTORE CON ID ASSOCIATO
PUT {{baseUrl}}/66a93681fe704129bec62ea5
Content-Type: application/json

{
  "avatar":
        "https://njhalloffame.org/wp-content/uploads/2021/04/generic-avatar-300x300.png"
}
### CANCELLA UN AUTORE CON ID ASSOCIATO
DELETE {{baseUrl}}/66a939713c314f505d26f793