@baseUrl=http://localhost:5000/authors

### RITORNA LA LISTA DEGLI AUTORI
GET {{baseUrl}}
###
GET {{baseUrl}}?page=1&perPage=5
### RITORNA IL SINGOLO AUTORE
GET {{baseUrl}}/66a938123c314f505d26f795
### CREA UN NUOVO AUTORE
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Giuseppe",
  "surname": "Esposito",
  "birthDate": "10/10/2010",
  "email": "andrea@sota.com",
  "avatar": "https://picsum.photos/300/300"
}
### MODIFICA UN AUTORE CON ID ASSOCIATO
PUT {{baseUrl}}/66aa721423ea2989207e7eb5
Content-Type: application/json

{
  "avatar":
        "https://njhalloffame.org/wp-content/uploads/2021/04/generic-avatar-300x300.png"
}
### CANCELLA UN AUTORE CON ID ASSOCIATO
DELETE {{baseUrl}}/66a939713c314f505d26f793

### RITORNA I POSTSBLOG DI UN AUTORE
GET {{baseUrl}}/66ad2855f9e65c7c2bc990cd/blogPosts
### RITORNA I POSTSBLOG DI UN AUTORE
GET {{baseUrl}}/66ad2c47cdac3f5495b31304/blogPosts